# (string) Title of your wiki
title: Civ13 Wiki
# (string) Description of your wiki
description: Civ13's Wiki Guide
# (boolean) Enable/disable wiki page list in sidebar
show_wiki_pages: false
# (integer) Maximum number of wiki page to shown in sidebar
show_wiki_pages_limit: 10
# (string) Specify branch rendered by gitpages allowing wiki tool buttons to work
git_branch: "master"
# (string) Url of logo image, it can be full, absolute or relative.
logo_url: "assets/images/civ13_logo.png"
baseurl: "/civ13-wiki" # the subpath of your site, e.g. /blog
relative_url: ""
url: "https://civ13.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# (string) The UA-XXXXX-Y code from google analytic to enable GA on your wiki
google_analytics: 
# (string) folder where wiki pages are stored, it's needed for tool buttons
wiki_folder: "wiki"
# (boolean) if you're using github wiki as submodule then this config
# must be enabled to allow tool buttons to work properly
use_github_wiki: false
# (boolean) Enable "Edit with Prose.io" button in tools, it's a 3rd party
# service to edit github markdown pages easily
use_prose_io: false
# Select search_engine component from:
# - js: it uses a built in javascript component that uses generated js object
# - js_rss: it uses a built in javascript component that uses generated  sitemap_full.xml to search inside your wiki with lunr library (slow and experimental)
# - github : it uses internal github repository search
# - google : it uses cse search bar, you need to configure google_cse_token
#
search_engine : "js"
# Setting google custom search engine for google
# cse search bar (https://cse.google.it/cse/)
google_cse_token: 

# (string) path of site root. Normally it's must be empty because _config.yml resides in the root of your repository.
# If you have _config.yml and your site in a subfolder, then change this config accordly 
site_root: 

#
# Jekyll configurations
#

# You can customize it changing default layout for all pages
# More info: https://jekyllrb.com/docs/configuration/
#
# git-wiki includes some internal themes that you can choose
# check _layouts folder
#
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

defaults:
 - 
    scope:
      path: "wiki"
    values:
      permalink: /:basename
 -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "git-wiki-bs-darkly"
 -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "git-wiki-bs-darkly"

sass:
    style: compressed
plugins:
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-gist
  - jekyll-mentions
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-remote-theme
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings
  - jemoji


#
# INCLUDING HOOKS
# They are optional, change them only if you need
# Check wiki documentation to learn how they work
#

inc_before_toc : 
inc_after_toc : 
inc_before_content : 
inc_after_content : 
inc_before_footer : 
inc_after_footer : 
inc_before_head : 
inc_after_head : 
inc_before_meta : 
inc_after_meta : 
inc_before_scripts : 
inc_after_scripts : 
inc_before_styles : 
inc_after_styles : 
inc_before_header : 
inc_after_header : 
inc_before_tail : 
inc_after_tail : 
inc_before_tools : 
inc_after_tools : 

inc_before_page_list :
inc_after_page_list :
inc_before_post_list :
inc_after_post_list :

repository: Civ13/civ13-wiki
github:
  repository_nwo: Civ13/civ13-wiki
  repository_url: https://github.com/Civ13/civ13-wiki
